### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by doggoli**
its pointless

### CODE REVIEW

**Comment by x-t** [comment]
the kid wants a free shirt, close it but don't mark it as spam thanks lol

**Comment by kriekprinsloo** [comment]
What's this about a free shirt?

**Comment by x-t** [comment]
> What's this about a free shirt?

https://hacktoberfest.digitalocean.com/

**Comment by JamesH65** [comment]
Sorry, but poluting our systems with crap like this is going to get reported as spam.

SPAM SPAM SPAM SPAM

**Pull request closed without merging**
